### ISSUE TITLE
getting a response 400 from plugin

### ISSUE THREAD

**Issue by whitty69** [tjackiw/graylog-plugin-jira#3]
Hi,

Great plugin :-) however ........

I'm getting the following error in graylog when the callback is called.

any ideas why?

Peter.

`2016-03-08 10:46:21,665 ERROR: org.graylog2.shared.rest.exceptionmappers.AnyExceptionClassMapper - Unhandled exception in REST resource
java.lang.RuntimeException: [JIRA] Unexpected HTTP response status 400
        at com.tjackiw.graylog2.plugin.jira.callback.JiraAlarmCallback.call(JiraAlarmCallback.java:76)
        at org.graylog2.rest.resources.streams.alerts.StreamAlertReceiverResource.sendDummyAlert(StreamAlertReceiverResource.java:168)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
`

**Comment by magicdude4eva** [comment]
I had similar issues - make sure that your plugin defaults match your Jira setup. In my case the default for issue-priority "P1" needed to change to "Minor". You might also have a different issue-type to the default of being "Bug".

**Comment by whitty69** [comment]
thanks.. finally got it work, but I to do as you mention, but I had to set values for all fields (even optional ones)

:-)

**Comment by magicdude4eva** [comment]
I reworked this plugin in another project - perhaps some of the new features will work for you - https://github.com/magicdude4eva/graylog-jira-alarmcallback
